Shubhamsaboo/awesome-llm-apps

chat_with_github/chat_github_llama3.py

I'm using here streamlit session sotrage to avoid reloading repo  eacj time new question is asked

Modification of chat_with_github_ollama3 to load repostory only once

---

investment_ai_agent/requirements.txt

Fix dependency exception in investment_agent.py. 
pip install yfinance

Update requirements.txt add yfinance

---

rag_tutorials/local_hybrid_search_rag/.gitignore
rag_tutorials/local_hybrid_search_rag/README.md
rag_tutorials/local_hybrid_search_rag/local_main.py
rag_tutorials/local_hybrid_search_rag/requirements.txt

done, working completely fine. no issues at all. used llama 3.2 3b Instruct

local llama version of the hybrid search RAG system

---

ai_agent_tutorials/ai_services_agency/agency.py

Fixed persistent issues in ai_services_agency/agency.py

---

ai_agent_tutorials/ai_legal_agent_team/README.md
ai_agent_tutorials/ai_legal_agent_team/main.py
ai_agent_tutorials/ai_legal_agent_team/requirements.txt

Everything works well. we just have a tiny issue which is mentioned at the end!
A Quick Short summary for @Shubhamsaboo :
this has 3 agents - Legal Researcher, Contract Analyst, Legal Strategist ; and a Agent Team with all of these called Team lead
and when a user gets to select an analysis type, where it has a pre defined query - and a particular agent will run when called the respective analysis type
- Contract Review - Done by Contract Analyst
- Legal Research - Done by Legal Researcher
- Risk Assessment - Done by Legal Strategist, Contract Analyst
- Compliance Check - Done by Legal Strategist, Legal Researcher, Contract Analyst
- Custom Queries - Done by Agent Team - Legal Researcher, Legal Strategist, Contract Analyst
The final response has 3 tabs - Detailed analysis, key points, …

#Proj 5 - AI Legal Agent Team

---

ai_agent_tutorials/ai_recruitment_agent_team/README.md
ai_agent_tutorials/multimodal_design_agent_team/requirements.txt
rag_tutorials/rag_database_routing/README.md
rag_tutorials/rag_database_routing/rag_database_routing.py
rag_tutorials/rag_database_routing/requirements.txt

yet to fix a few features, working on them

RAG with database routing - first initialization

---

ai_agent_tutorials/ai_tic_tac_toe_agent/README.md
ai_agent_tutorials/ai_tic_tac_toe_agent/ai_tic_tac_toe_agent.py
ai_agent_tutorials/ai_tic_tac_toe_agent/requirements.txt

OpenAI 4o, Deepseek v3, Gemini 1.5 Flash are players

New Project: AI vs AI Tic Tac Toe Game 

---

ai_agent_tutorials/ai_data_analysis_agent/README.md
ai_agent_tutorials/ai_data_analysis_agent/ai_data_analyst.py
ai_agent_tutorials/ai_data_analysis_agent/requirements.txt

built with phidata's duckdb custom agent!

Added AI Data Analysis folder 

---

ai_agent_tutorials/ai_game_design_agent_team/game_design_agent_team.py
ai_agent_tutorials/ai_game_design_agent_team/requirements.txt

See the latest update from AutoGen: https://github.com/microsoft/autogen

Upgrade AutoGen API to v0.4

---

ai_agent_tutorials/ai_customer_support_agent/README.md
ai_agent_tutorials/ai_customer_support_agent/customer_support_agent.py

mem0 changed its config functionality, where in you can have a model key value in config json format. that's causing the error. 
also changed the readme a little, there was an error in qdrant - running qdrant locally. raised an issue https://github.com/qdrant/landing_page/issues/1403
CAN merge this. app works fine

changes made to the AI customer support Agent

---

rag_tutorials/rag_chain/README.md
rag_tutorials/rag_chain/app.py
rag_tutorials/rag_chain/requirements.txt

An advanced Insight Retrieval System designed to help users gain meaningful insights from research papers and documents in the pharmaceutical domain.

rag_chain added to rag_tutorials

---

ai_agent_tutorials/ai_game_design_agent_team/game_design_agent_team.py

chore: update game_design_agent_team.py

---

ai_agent_tutorials/ai_competitor_intelligence_agent_team/README.md
ai_agent_tutorials/ai_competitor_intelligence_agent_team/competitor_agent_team.py
ai_agent_tutorials/ai_competitor_intelligence_agent_team/requirements.txt

- added perplexity sonar pro for search similar URLS (better search)
- exa ai search is also there
- using extract feature of firecrawl (which released recently)
- previously used firecrawltools through agno -> now changed!

REVAMP of AI Competitor Intelligence Agent Team (CAN MERGE)

---

ai_agent_tutorials/ai_blog_to_podcast_agent/README.md
ai_agent_tutorials/ai_blog_to_podcast_agent/blog_to_podcast_agent.py
ai_agent_tutorials/ai_blog_to_podcast_agent/requirements.txt
ai_agent_tutorials/ai_models_lab_music_generator_agent/README.md
ai_agent_tutorials/ai_models_lab_music_generator_agent/models_lab_music_generator_agent.py
ai_agent_tutorials/ai_models_lab_music_generator_agent/requirements.txt

Add ModelsLab Music Generator Agent
- Streamlit app
- README.md

Add ModelsLab Music Generator Agent

---

starter_ai_agents/web_scrapping_ai_agent/local_ai_scrapper.py

chore: fix typo

---

advanced_ai_agents/multi_agent_apps/agent_teams/ai_game_design_agent_team/README.md

The run command in the README was incorrect as it included a redundant path. This commit fixes the command to align with the provided 'cd' instruction.

Fix: Corrects run command in Game Design Agent README

---

advanced_ai_agents/multi_agent_apps/agent_teams/ai_competitor_intelligence_agent_team/competitor_agent_team.py

- Comment out unused exa_py import
- Improve error handling for Firecrawl API responses
- Enhance competitor analysis UI with better feedback
- Replace agent-based comparison with DataFrame approach
- Add extraction success/failure tracking

fix: improve competitor agent

---

ai_agent_framework_crash_course/google_adk_tutorials/1_starter_agent/README.md

Updated the stale directory links within the README file

fix: update tutorial links for improved navigation and clarity

---

mcp_ai_agents/browser_mcp_agent/README.md
mcp_ai_agents/browser_mcp_agent/main.py
mcp_ai_agents/browser_mcp_agent/mcp_agent.config.yaml

Playwright MCP Server seems to perform better than Puppeteer MCP Server.
Updates:
- Updated MCP Server to be [Playwright](https://github.com/microsoft/playwright)
- Swapped the demo flow to go to the Awesome LLM Apps Repo instead
- Updated the demo video to be the updated demo flow and MCP server
https://github.com/user-attachments/assets/a01e09fa-131b-479a-8df3-2d1a61fd80f3

[Browser MCP Agent] Updating MCP Server in Demo to Playwright

---

advanced_ai_agents/multi_agent_apps/agent_teams/ai_real_estate_agent_team/local_ai_real_estate_agent_team.py

This small PR fixes a small syntax bug in `local_ai_real_estate_agent_team.py` of missing `else`-body.

fix: resolve bug in `local_ai_real_estate_agent_team.py`
